
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base          # or ../../base if you have a base folder

components:
  - ../../components/with-shipping-wasm
  - ../../components/with-recommendation-wasm
  - ../../components/with-cart-docker
  - ../../components/with-node-selector
  - ../../components/container-pull-secrets