apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- path: checkoutservice.yaml
  target:
    kind: Deployment
    name: checkoutservice
- path: frontend.yaml
  target:
    kind: Deployment
    name: frontend
resources:
- cartservice-wasm.yaml
