apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    spec:
      containers:
      - name: server
        env:
        - name: SHIPPING_SERVICE_ADDR
          value: "130.149.158.32:51010"
