apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- path: secert.yaml
  target:
    kind: Secret
    name: registry-credentials
- path: imagePullSecret.yaml
  target:
    kind: Deployment