apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXQudHUtYmVybGluLmRlOjUwMDAiOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiYmFzdGkud2VybmVyIiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiU1gwV1FrdjlZd3hKN3NDeV8xZFhmRzg2TVFwMU9taDRkQWsuMDEuMHowb2Jld3ZmIiwKICAgICAgICAgICAgImVtYWlsIjoiYmFzdGkud2VybmVyIiwKICAgICAgICAgICAgImF1dGgiOiJZbUZ6ZEdrdWQyVnlibVZ5T2xOWU1GZFJhM1k1V1hkNFNqZHpRM2xmTVdSWVprYzROazFSY0RGUGJXZzBaRUZyTGpBeExqQjZNRzlpWlhkMlpnPT0iCiAgICAJfQogICAgfQp9